### ISSUE TITLE
Proposal doc for Diego review

### ISSUE THREAD

**Issue by LiliBear1** [LiliBear1/Sports-Project#2]
- Project Title
- Project Description
- User Stories
- Wireframe or Sketch of Design
- APIs
- Rough Breakdown of task
- Team

**Comment by cedagbo** [comment]
Great teamwork guys

**Comment by LiliBear1** [comment]
@vbugana @Kaiyfa @cedagbo Can one of you close out please now that I have shared the doc and Diego has approved

**Comment by cedagbo** [comment]
Done!
