### ISSUE TITLE
MVP Wireframe

### ISSUE THREAD

**Issue by LiliBear1** [LiliBear1/Sports-Project#4]

**Comment by LiliBear1** [comment]
@Kaiyfa can you please add me to your FIGMA file

**Comment by LiliBear1** [comment]
@vbugana @Kaiyfa @cedagbo Please review and approve or add comments

**Comment by Kaiyfa** [comment]
@LiliBear1 yes I'll do it by tonight.

**Comment by cedagbo** [comment]
Alright. I'll have a look asap

**Comment by cedagbo** [comment]
As things stand right now, wireframe looks good. We can  improve it along the way through Figma as we discussed earlier.

**Comment by LiliBear1** [comment]
Basic file has been created using slide and is in the proposal doc, @Kaiyfa and I will collab on Figma to make it more presentable
