### ISSUE TITLE
Create HTML

### ISSUE THREAD

**Issue by LiliBear1** [LiliBear1/Sports-Project#7]
To pad out Boilerplate and add link refs and Bootstrap where relevant

**Comment by LiliBear1** [comment]
@cedagbo @Kaiyfa @vbugana I have pushed the HTML file with Bootstrap, css, JQuery links in, please review and add comments. As discussed , have removed the manager section as we deemed it irrelevant for user.

**Comment by Kaiyfa** [comment]
@LiliBear1, I think that it is relevant to add a delete button in order to delete the search history as we're using a local storage.
          <button id="clear-city-names" type="button" class="btn btn-primary btn-sm" title="Delete city list">X</button>
